### ISSUE TITLE
React & Redux group project: set up your Kanban board

### ISSUE THREAD

**Issue by myaserkhan** [myaserkhan/React-Redux-Space-Travelers-Hub#25]
Hi there, we are a group of two people @myaserkhan @johnkioko.

 Link to GitHub project: https://github.com/myaserkhan/React-Redux-Space-Travelers-Hub/projects/1

**Comment by mckent05** [comment]
Hi @myaserkhan,

# STATUS: APPROVED ✔️  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![approved](https://user-images.githubusercontent.com/73607512/203015339-bca6e481-8253-4a72-996a-b78496841245.gif)


## Highlights
- Your Kanban is setup correctly 👍 👍 
- All tasks have been evenly assigned and distributed 👏 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
